// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWK34R2GRbaG1lTzy83PT-MnmBN-ethpU',
    appId: '1:1005996252917:web:8b5c84f313f93f83b5efbc',
    messagingSenderId: '1005996252917',
    projectId: 'flutechat-de50a',
    authDomain: 'flutechat-de50a.firebaseapp.com',
    storageBucket: 'flutechat-de50a.appspot.com',
    measurementId: 'G-H1EQ0YJ6D1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQiB1DTmpYqyICan1AeMawQJ5hda1Eqf4',
    appId: '1:1005996252917:android:5ed67acb448b7a91b5efbc',
    messagingSenderId: '1005996252917',
    projectId: 'flutechat-de50a',
    storageBucket: 'flutechat-de50a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqFPaE9slMq6oHn83Iu1EXfV1TDPiMAgM',
    appId: '1:1005996252917:ios:3e54d1501ead307fb5efbc',
    messagingSenderId: '1005996252917',
    projectId: 'flutechat-de50a',
    storageBucket: 'flutechat-de50a.appspot.com',
    iosBundleId: 'com.virturio.flutechat',
  );
}
